name: issue-comment-workflow
on: issue_comment

jobs:
  pr-comment:
    if : ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
    - name: pr comment
      run: echo {{This is a comment on a pull request}}
  
  issue-comment:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
    - name: issue comment
      run: echo {{This is a comment on an issue}