name: multiple-event-workflow
on: 
  push:
  issues:
    types: [opened]
  workflow_dispatch: # 수동으로 트리거할 때,

jobs:
  multiple-evnet-job:
    runs-on: ubuntu-latest # 어떤 환경에서 실행될지 지정.
    steps:
      - name: step1 # 각 스텝의 이름 지정.
        run : echo hello world # 쉘 명령어 실행.
      - name : step2
        run : |
          echo "This is step 2"
          echo "Multiple lines in a single step"      



