name: pull-request-workflow
on: 
  pull_request:
    types: [opened]

jobs:
  pull-request-job : 
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run : echo "Hello from pull request workflow"
      - name: step2
        run : |
          echo "This is step 2 of pull request workflow"
          echo "Multiple lines in a single step"

# 변경사항을 코드 저장소에 합병시키려고 할 때 사용한다!!