



# - 과거에 실행된 워크플로우를 재실행
# - 성공, 실패 여부와 상관없이 재실행 가능
# - 트리거된 그 시점을 다시 실행

오해
- step1. 과거에 이미 실행된 워크플로우가 있음
- step2. 파일을 수정
- step3. 과거에 실행된 워크플로우를 리턴하면 수정한 내용이 반영

실제
- step1. 과거에 이미 실행된 워크플로우가 있음
- step2. 파일을 수정
- step3. 과거에 실행된 워크플로우를 리턴해도 수정한 내용이 반영 안됨
- step4. 수정한 파일이 포함된 후에 워크플로우가 트리거되어야 반영