name: artifact
on: push

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "This is a test file" > hello.txt

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-name
          path: ./hello.txt

  download-artifact:
    runs-on: ubuntu-latest
    needs: [upload-artifact]
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact-name
          path: ./
      - name: check
        run: cat ./hello.txt

# - 워크플로우 실행 중 생성된 파일 또는 파일 모음
# - 워크플로우가 종료된 후에도, 데이터 유지 (90일)
# - 다운로드 가능
# - 깃헙 마켓플레이스에 정의된 공식 액션
#     - upload-artifact
#     - download-artifact