name: branch-filter
on:
  push:
    branches: ["dev-test"]

jobs:
  branch-filter:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "This workflow runs only on pushes to the dev branch"

# - 이벤트가 특정 조건에 부합할 때 실행
#     - 워크플로우 실행을 더 효과적으로 제어
# - branch, path, tag
# - 특정 branch에서 실행
# - 특정 Path에서 실행
# - 특정 tag에서 실행

# - 특정 branch에서 실행
# - ex)
#     - dev, master branch 중에서 master branch로 push 해야만 실행.