name: tag-filter
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # v1.0.0, v2.1.3 등과 같은 태그 패턴에 매칭될 때 실행, v1.0 or v1.0.0-beta 등은 매칭 안됨.

jobs:
  tag-filter:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "This workflow runs only when tags matching the pattern vX.Y.Z are pushed"

# - 특정 태그에서 실행
#     - ex) v1.0.0 으로 태깅해야 실행
# - push event에서만 사용 가능
# - 태그를 사용하는 방법
#     - git tag <tag-name>