name: branch-filter
on:
  push:
    branches: ["dev-test"]

jobs:
  branch-filter:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "This workflow runs only on pushes to the dev branch"