name: timeout
on: push

jobs:
  timeout:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - name: Long running step
      run: |
        count=0
        while true; do
          echo "Running... $count minutes"
          count=$((count + 1))
          sleep 1
        done
    - name: echo
      run: echo "This step will not be reached if the timeout occurs."