name: workflow-dispatch
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'set-name'
        required: true
        default: 'github-actions'
        type: string

      environment:
        description: 'set-env'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - qa
        - prod

jobs:
  push-job : 
    runs-on: ubuntu-latest # 어떤 환경에서 실행될지 지정.
    steps:
      - name: step1 # 각 스텝의 이름 지정.
        run : echo hello world # 쉘 명령어 실행.
      - name : step2
        run : |
          echo "This is step 2"
          echo "Multiple lines in a single step"
      - name: "echo inputs"
        run : |
          echo ${{inputs.name}}
          echo ${{inputs.environment}}